### ISSUE TITLE
How Can I Change the main Color

### ISSUE THREAD

**Issue by bestony** [ponylang/mkdocs-theme#4]
## Description

is here a document for user to set there documents?

I need a document to set my doucment

### Expected behavior

a document to tell me how to set my document or 

I pefer get a settings item at mkdocs.yml to change to **color**、**ICON** and **others**.

### Actual behavior

Nothing I can found.

### Package versions

* Python: 3.6
* MkDocs: 0.17.3
* Material: newest

### Project configuration

``` yaml
theme: ponylang
markdown_extensions:
    - admonition
    - toc:
        permalink: True
        separator: "_"
    - sane_lists
```

### System information

* OS: macOS
* Browser: Chrome
